# Generated by Django 4.2.2 on 2023-06-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancodedados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('corredor', models.CharField(max_length=100)),
                ('prateleira', models.CharField(max_length=100)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.produto')),
            ],
        ),
    ]
