# Generated by Django 4.2.2 on 2023-06-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancodedados', '0003_compra_corredor_fiscal_prateleira_relatoriocompra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.cargo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.setor')),
            ],
        ),
        migrations.CreateModel(
            name='SetorFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaDePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanais', models.IntegerField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.funcionario')),
            ],
        ),
    ]
